# Generated by Django 2.2.5 on 2020-04-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mushroom',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='mushroom',
            old_name='started_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='mushroom',
            name='title',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
    ]
