# Generated by Django 2.2.5 on 2020-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0002_auto_20200419_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='mushroom',
            name='mushroom_type',
            field=models.CharField(blank=True, choices=[('Chanterelle', 'Chanterelle'), ('Shiitake', 'Shiitake'), ('Portobello', 'Portobello')], max_length=30, null=True),
        ),
    ]
