# Generated by Django 2.2.5 on 2020-04-22 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0003_mushroom_mushroom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
