# Generated by Django 2.2.5 on 2020-04-23 16:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0004_auto_20200422_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='mushroom_type',
            field=models.CharField(choices=[('Chanterelle', 'Chanterelle'), ('Shiitake', 'Shiitake'), ('Portobello', 'Portobello')], default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
