# Generated by Django 2.2.5 on 2020-04-23 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0006_auto_20200423_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mushroom',
            old_name='mushroom_type',
            new_name='mushroom_choices',
        ),
    ]
