# Generated by Django 2.2.5 on 2020-04-23 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mushrooms', '0007_auto_20200423_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mushrooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
