# Generated by Django 2.2.5 on 2020-03-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_site', '0003_auto_20200329_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
