# Generated by Django 2.2.5 on 2020-04-20 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mushroom_site', '0004_auto_20200329_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='selected_mushroom',
        ),
    ]
